<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-95104MM" ignored="0" name="LoginTest" tests="2" failures="1" timestamp="2021-09-25T14:01:50 IST" time="26.788" errors="0">
  <testcase name="loginTest" time="4.559" classname="Automation.Salesforce.LoginTest"/>
  <testcase name="getTextStatus" time="1.287" classname="Automation.Salesforce.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [a customer] but found [Not a customer?]">
      <![CDATA[java.lang.AssertionError: expected [a customer] but found [Not a customer?]
at Automation.Salesforce.LoginTest.getTextStatus(LoginTest.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- getTextStatus -->
</testsuite> <!-- LoginTest -->
